[package]
name = "able-sandbox"
version = "0.1.0"
authors = ["able"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
serde = "1.0"
toml = "0.5"
discord-rpc-client = "0.3.0"
